// React/src/components/Sidebar.js
import React, { Component } from 'react';

class Sidebar extends Component {
    render() {
        return(
            <aside id="sidebar">
            <div id="nav-blog" className="sidebar-item">
                <h3>puedes hacer esto</h3>
                <a href="" className="btn btn-success"> Crear Articulo</a>
            </div>
    
            <div id="search" className="sidebar-item">
                <h3>Bucador</h3>
                <p>Encuentra el articulo que buscas </p>
                <form action="">
                    <input type="text" name="search" />
                    <input type="submit" name="submit" value="Buscar" className="btn" />
                </form>
            </div>
        </aside>
        );
    }
}

export default Sidebar;

// angular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';



@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  public search: string;

  constructor( private router: Router ) { }

  searchArticles(data: string) {
    this.router.navigate(['/search', data]);
  }

  ngOnInit() {

  }

}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>puedes hacer esto</h3>
        <a [routerLink]="['/new-article']" class="btn btn-success"> Crear Articulo</a>
    </div>

    <div id="search" class="sidebar-item">
        <h3>Bucador</h3>
        <p>Encuentra el articulo que buscas </p>
        <form action="" (ngSubmit)="searchArticles(search)">
            <input type="text" name="search" #searchs="ngModel" [(ngModel)]="search" />
            <input type="submit" name="submit" value="Buscar" class="btn" />
        </form>
    </div>
</aside>

<div class="clearfix"></div>
